# Exported from MPLAB IDE project `PIC24UART1.mcp' on Sun May 06 13:48:52 2007.

"PIC24UART1.hex" : "PIC24UART1.cof"
	"C:\Program Files\Microchip\MPLAB C30\bin\pic30-bin2hex.exe" "PIC24UART1.cof"

"PIC24UART1.cof" : "PIC24UART1.o"
	"C:\Program Files\Microchip\MPLAB C30\bin\pic30-gcc.exe" -mcpu=24HJ256GP610 "PIC24UART1.o" -o"PIC24UART1.cof" -Wl,-L"C:\Program Files\Microchip\MPLAB C30\lib",-Tp24HJ256GP610.gld,-Map="PIC24UART1.map",--report-mem

"PIC24UART1.o" : "PIC24UART1.c" "c:\program files\microchip\mplab c30\bin\..\support\h\P24HJ256GP610.h" "C:\WINDOWS\Desktop\PIC24\PIC24UART1.c"
	"C:\Program Files\Microchip\MPLAB C30\bin\pic30-gcc.exe" -mcpu=24HJ256GP610 -x c -c   "PIC24UART1.c" -o"PIC24UART1.o" -g -Wall

clean : 
	del "PIC24UART1.o" "PIC24UART1.cof" "PIC24UART1.hex"

